Acme\StoreBundle\Entity\Product:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: integer
        return:
            type: string
            length: 255
    lifecycleCallbacks: {  }
