parameters:
    database_driver: pdo_pgsql
    database_host: 127.0.0.1
    database_port: '5433'
    database_name: symfony2
    database_user: postgres
    database_password: postgres
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: f58b662efc3df4037a1e09ba199709fb7714aed1
    database_path: null
